name: Basic Swift Workflow
# This workflow is triggered on pushes to the repository.
on:
  push:

jobs:
  test:
    # Job name is Test
    name: Test
    # This job runs on macOS
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.1,name=iPhone X']
        xcode: ['/Applications/Xcode_10.1.app/Contents/Developer']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Bundle Install
        run: bundle install
        env:
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
      - name: Dependencies
        run: |
          carthage bootstrap --no-use-binaries --platform iOS --cache-builds
          bundle exec pod install
        env:
          DEVELOPER_DIR: ${{ matrix.xcode }}
      - name: Build and test
        run: bundle exec fastlane scan --destination "${destination}" --scheme "YOUR_APP_SCHEME"
        env:
          destination: ${{ matrix.destination }}
          DEVELOPER_DIR: ${{ matrix.xcode }}
      - name: Archive Failed Tests artifacts
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: FailureDiff
          path: YouAppTests/FailureDiffs
      - name: Releasing
        run: bundle exec fastlane release
        env:
          DEVELOPER_DIR: ${{ matrix.xcode }}
