name: Swift Project Build Test

on: 
  push:
    paths-ignore:
    - '**/BLT.app'

jobs:
  build:
    name: Build App
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Start xcodebuild test
      run: |
        xcodebuild clean -workspace BLT/BLT.xcworkspace -scheme BLT -destination "platform=iOS Simulator,name=iPhone 8"
        echo Cleaning Done
        echo Starting Build...
        xcodebuild -workspace BLT/BLT.xcworkspace -scheme BLT -destination "platform=iOS Simulator,name=iPhone 8" 
        echo Build Done
        echo Copying App File...
        cp -R /Users/runner/Library/Developer/Xcode/DerivedData/*/Build/Products/Debug-iphonesimulator/BLT.app ./BLT
        echo App File Copied
        echo Committing Files...
        git commit -a -m "Upload Built App"
        echo Files Committed
        echo Pushing Files...
        git push
        echo Push Done
