name: Swift Tests

on: 
  push:

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Start xcodebuild test
      run: xcodebuild clean test -project BLT.xcworkspace -scheme BLT -destination "platform=iOS Simulator,name=iPhone 8"
