name: Swift Project Build Test

on: 
  push:
    paths-ignore:
    - '**/BLT.app'

jobs:
  build:
    name: Build App
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Start xcodebuild test
      run: |
        xcodebuild clean -workspace BLT/BLT.xcworkspace -scheme BLT -destination "platform=iOS Simulator,name=iPhone 8"
        xcodebuild -workspace BLT/BLT.xcworkspace -scheme BLT -destination "platform=iOS Simulator,name=iPhone 8" 
        cp -R /Users/student/Library/Developer/Xcode/DerivedData/*/Debug-iphonesimulator/BLT.app ./BLT
        git commit -a -m "Upload Built App"
        git push
